uploads = []

[[generated]]
id = "BqPHghHfz7gbbJ8VFvUqB"
uri = "file://artifacts/foldr-storage/public/icon-foldr-generated.png"
type = "image"
title = "FOLDR crystal folder app icon"

[[outputs]]
id = "xSJwbZtJr-0Z68erKul8r"
uri = "file://artifacts/foldr-storage/public/favicon.svg"
type = "image"
title = "foldr.storage logo (SVG)"

[[outputs]]
id = "FFDBQal0__TAOA5YqvjkH"
uri = "file://artifacts/foldr-storage/public/folder-icon.svg"
type = "image"
title = "Folder icon (SVG) — transparent background"
